### ISSUE TITLE
A tool for showing the tree structure would be nice.

### ISSUE THREAD

**Issue by KleinerNull** [spurin/xmldataset#5]
As the title said. A tree showing method would be nice, so you can use it to create blank profiles. This would save energy since you don't need to copy/paste the xml string to get a blank profile string ready.

Could look like that:

```
xml = """<?xml version="1.0"?>
<colleagues>
    <colleague>
        <title>The Boss</title>
        <phone>+1 202-663-9108</phone>
        <email>boss@the_company.com</email>
    </colleague>
    <colleague>
       <title>Admin Assistant</title>
        <phone>+1 347-999-5454</phone>
        <email>admin@the_company.com</email>
    </colleague>
    <colleague>
        <title>Minion</title>
        <phone>+1 792-123-4109</phone>
        <email>minion@the_company.com</email>
    </colleague>
</colleagues>"""

show_tree(xml) =>

"""
colleagues
    colleague
        title
        phone
        email"""
```

This also could open some possibilities for automation. Imagine you could offer a default profile, if no profile was passed in. Just using this tree and concatenate 'dataset:parent' for every child. Just an idea.

**Comment by spurin** [comment]
I think we should be able to do this, the logic is already there for checking whether or entries exist in the profile, marking this as an enhancement.

**Comment by tinkerbotfoo** [comment]
I was also thinking this might be a useful utility to create the profile. This way you dont need to create a profile from scratch, you can just go and edit the tree structure to create the profile.

**Comment by tinkerbotfoo** [comment]
I can take a stab at it. Any guidance or advice is much appreciated ...

**Comment by spurin** [comment]
Pull requests are always welcome with xmldataset 👍   For this, we'd need to parse the xml in the same way the profile parser does, instead of comparing against the profile we'd need to build a corresponding structure detailing the layout (a dict), then prior to the return, convert the dict to a profile type structure.

**Comment by tinkerbotfoo** [comment]
I didn't know where to split the existing logic and include this functionality. So i took the shorter route to get the job done due to project constraints. Please review and lemme know your comments. 

**To Do:**
1. Current implementation is limited to the xml nodes. It doesn't expand the attributes of the nodes into the profile. It can be done in another update.

2. While using this my team also felt that we can extend the profile gen function and data profiling stats at each level. This will be useful to know which nodes are used quite often.

lemme know your thoughts.

**Comment by tinkerbotfoo** [comment]
Looks like python 3 build is breaking at this line (list assignment/ in place modification) in the pull request #12 . 
`path_list[p_idx]= str(re.sub('\[.+]','',item))`

Its works fine in python 2.7. I tried to resolve the issue. I haven't worked much with python 3. Appreciate if you can help ....

**Comment by tinkerbotfoo** [comment]
Fixed the python 3 issue. Plz check and lemme know. I am working on the other 2 ToDo items.

**Comment by tinkerbotfoo** [comment]
Implemented the first todo: feature to add include_attributes flag to include the attributes in the profile output as child of the element. Also added a new test for this feature.

"number", "id" would not show up if the include_attributes flag is set to false., since they are attributes of xml elements.

plz review/test and lemme know your thoughts

```
catalog
	lowest
		number
		specificbefore
			specificvalue
		book
			id
			optionalexternalstart
				externaldata
			author
			title
			genre
			price
			publish_date
			description
			optionalexternalend
				externaldata
		book2
			id
			author
			title
			genre
			price
			publish_date
			description
		specificafter
			specificvalue
```

**Comment by spurin** [comment]
Thanks for previous comments, closing issue
